#!/bin/bash

export DATATORRENT_HOME=/opt/datatorrent/current
export JAVA_HOME=/usr/lib/jvm/java-8-oracle
export HADOOP_HOME=/opt/hadoop
export HADOOP_PREFIX=/opt/hadoop
export HADOOP_YARN_HOME=/opt/hadoop
export HADOOP_HDFS_HOME=/opt/hadoop
export HADOOP_COMMON_HOME=/opt/hadoop
export HADOOP_MAPRED_HOME=/opt/hadoop
export HADOOP_CONF_DIR=/opt/hadoop/etc/hadoop
export HDFS_CONF_DIR=/opt/hadoop/etc/hadoop
export YARN_CONF_DIR=/opt/hadoop/etc/hadoop
export YARN_HOME=/opt/hadoop
export SQOOP_HOME=/opt/sqoop
export PIG_HOME=/opt/pig
export PATH=${PATH}:${DATATORRENT_HOME}/bin:${PIG_HOME}/bin:${SQOOP_HOME}/bin:${HADOOP_HOME}/bin

sudo -Eu dtadmin dtgateway start -f
